// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOnBrkIAXIQ4Q1bYeH7Y7VwL84YY7bCuI',
    appId: '1:397114841675:web:0e018355fabb3a3cbf8bce',
    messagingSenderId: '397114841675',
    projectId: 'lc-engineer',
    authDomain: 'lc-engineer.firebaseapp.com',
    storageBucket: 'lc-engineer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACrCX6jeciJH_loNYpPstoyu1Cy2Sy8VY',
    appId: '1:397114841675:android:9d792e92612125d2bf8bce',
    messagingSenderId: '397114841675',
    projectId: 'lc-engineer',
    storageBucket: 'lc-engineer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaU2tDAlDABv3ciQLmM5L5yPHKqdImEg',
    appId: '1:397114841675:ios:a1cce6c26cc48229bf8bce',
    messagingSenderId: '397114841675',
    projectId: 'lc-engineer',
    storageBucket: 'lc-engineer.appspot.com',
    iosClientId: '397114841675-nng5v10bdhkb3mofv8hn68j51qt20l7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADaU2tDAlDABv3ciQLmM5L5yPHKqdImEg',
    appId: '1:397114841675:ios:2c4e0639110b4c4ebf8bce',
    messagingSenderId: '397114841675',
    projectId: 'lc-engineer',
    storageBucket: 'lc-engineer.appspot.com',
    iosClientId: '397114841675-4sm8aceip2c9af0jrvd4p3jgb7ae9ne1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOnBrkIAXIQ4Q1bYeH7Y7VwL84YY7bCuI',
    appId: '1:397114841675:web:77929760605f103ebf8bce',
    messagingSenderId: '397114841675',
    projectId: 'lc-engineer',
    authDomain: 'lc-engineer.firebaseapp.com',
    storageBucket: 'lc-engineer.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAOnBrkIAXIQ4Q1bYeH7Y7VwL84YY7bCuI',
    appId: '1:397114841675:web:268ec2f582e3d287bf8bce',
    messagingSenderId: '397114841675',
    projectId: 'lc-engineer',
    authDomain: 'lc-engineer.firebaseapp.com',
    storageBucket: 'lc-engineer.appspot.com',
  );
}
