// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKsU35rvL2L1LWPrKYSceBUfToTiNiB-E',
    appId: '1:811700888823:web:bc042590a3ab543be1dff2',
    messagingSenderId: '811700888823',
    projectId: 'engineer-b0988',
    authDomain: 'engineer-b0988.firebaseapp.com',
    storageBucket: 'engineer-b0988.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzcpVDUrQjZn901N20R5x2eteDBYfhUMw',
    appId: '1:811700888823:android:df62733a423b8c22e1dff2',
    messagingSenderId: '811700888823',
    projectId: 'engineer-b0988',
    storageBucket: 'engineer-b0988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2xwTrhUSn02Hx6vzD8FwKJkcP9zIuv_I',
    appId: '1:811700888823:ios:ff64349695ba6ea6e1dff2',
    messagingSenderId: '811700888823',
    projectId: 'engineer-b0988',
    storageBucket: 'engineer-b0988.appspot.com',
    iosClientId: '811700888823-b9qmngraojm2bggppg6n7t9cbrh55eao.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
