// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKF6mWwonXbLlbVQVjdy0hxgMjLlgAo1U',
    appId: '1:76119550257:android:269775ac286c415d3ea810',
    messagingSenderId: '76119550257',
    projectId: 'auth-d3517',
    storageBucket: 'auth-d3517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAF7guYY8rcp_9d4rIJBsyc8a13mWlSoA',
    appId: '1:76119550257:ios:21d6eaa7a39c84bf3ea810',
    messagingSenderId: '76119550257',
    projectId: 'auth-d3517',
    storageBucket: 'auth-d3517.appspot.com',
    iosClientId: '76119550257-vl8eo0jnov2de6dm4ka9m4ocdtoksueo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOlt3cCtR19QtzHRTpIDXWOLjh0qTfP78',
    appId: '1:76119550257:web:cc1c5e07d0d88a1d3ea810',
    messagingSenderId: '76119550257',
    projectId: 'auth-d3517',
    authDomain: 'auth-d3517.firebaseapp.com',
    storageBucket: 'auth-d3517.appspot.com',
  );
}
